name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Execute unit tests
      run: dotnet test
    
    - name: Build
      run: dotnet build -c release --no-restore
      
    - name: Release
      if: ${{ endsWith(github.ref_name, '-pre') }}
      uses: softprops/action-gh-release@v0.1.15
      with:
        prerelease: true
        body: Automated release of ${{ github.ref_name }}
        files: Silkworm/bin/Release/net6.0/Silkworm.dll

    - name: Release
      if: ${{ !endsWith(github.ref_name, '-pre') }}
      uses: softprops/action-gh-release@v0.1.15
      with:
        body: Automated release of ${{ github.ref_name }}
        files: Silkworm/bin/Release/net6.0/Silkworm.dll
